@extends('layouts.app')
@section('content')
<section class="mx-auto max-w-7xl px-5 pb-20 pt-16 lg:px-8 lg:pt-24">
    <div class="grid items-center gap-14 lg:grid-cols-[1.15fr_.85fr]">
        <div>
            <p class="mb-6 font-display text-xs font-bold uppercase tracking-[.24em] text-coral">[ inspection toolkit ]</p>
            <h1 class="max-w-4xl font-display text-5xl font-bold leading-[.95] tracking-tight lg:text-8xl">Inspect the<br><span class="text-coral">digital surface.</span></h1>
            <p class="mt-8 max-w-xl text-lg leading-8 text-ink/65 dark:text-[#b8ffcf]/65">A practical OSINT and cybersecurity toolkit for inspecting image metadata, geolocation, website security, phone intelligence, and public social footprints. Start with one signal, then follow the evidence.</p>
            <div class="mt-8 flex items-center gap-3 font-display text-xs text-ink/50 dark:text-[#b8ffcf]/50"><span class="h-2 w-2 animate-pulse rounded-full bg-coral"></span> toolkit online <span class="text-coral">//</span> select an inspection module</div>
        </div>
        <div class="relative border border-coral/40 bg-[#07110c] p-6 text-[#b8ffcf] shadow-[0_0_40px_rgba(57,255,136,.1)] dark:bg-paper dark:text-ink">
            <div class="mb-7 flex items-center justify-between border-b border-[#b8ffcf]/15 pb-4 text-xs text-[#b8ffcf]/50 dark:border-ink/15 dark:text-ink/50"><span>~/amazing-tools</span><span>v1.0.0</span></div>
            <p class="font-display text-2xl font-bold text-[#b8ffcf]/45 dark:text-ink/45">$ ls -la ./inspection-tools</p>
            <div class="mt-5 space-y-3 font-display text-sm"><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> username-hunter <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> phone-intelligence <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> reverse-phone-osint <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> social-account-correlation <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> image-intelligence <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> domain-intelligence <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p><p><span class="text-[#b8ffcf]/45 dark:text-ink/45">drwx</span> website-security-inspector <span class="text-[#b8ffcf]/45 dark:text-ink/45">[ active ]</span></p></div>
            <p class="mt-8 border-t border-[#b8ffcf]/15 pt-4 font-display text-xs text-[#b8ffcf]/45 dark:border-ink/15 dark:text-ink/45">8 modules indexed � 7 ready to execute</p>
        </div>
    </div>
</section>
<section class="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div class="border border-amber-400/70 bg-amber-400/10 p-5 shadow-[0_0_24px_rgba(251,191,36,.12)]"><div class="flex flex-col justify-between gap-4 border-l-4 border-amber-400 pl-4 md:flex-row md:items-center"><div><p class="font-display text-xs font-bold uppercase tracking-[.2em] text-amber-300">[ ! ] privacy_protocol / read_before_scanning</p><p class="mt-2 max-w-3xl text-sm leading-6 text-amber-100/80">WARNING: Uploaded images and scan data are not stored. All processing is temporary, with no permanent storage. Public lookup targets may contain sensitive information, so review permissions before scanning or sharing results.</p></div><a href="{{ route('privacy') }}" class="shrink-0 border border-amber-300 px-4 py-2 font-display text-xs font-bold uppercase tracking-wider text-amber-300 hover:bg-amber-300 hover:text-[#07110c]">read privacy ?</a></div></div></section>
<section class="border-y border-ink/10 dark:border-[#b8ffcf]/10"><div class="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div class="mb-3 flex items-end justify-between gap-4"><div><p class="font-display text-xs uppercase tracking-[.2em] text-coral">[ identity / people ]</p></div></div></div></section>
<section class="mx-auto max-w-7xl px-5 py-12 lg:px-8">
    <div class="grid  sm:grid-cols-2 lg:grid-cols-4">
        <a href="{{ route('username-hunter.index') }}" class="group relative border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[UH]</span><p class="mt-8 font-display text-lg font-bold">Username Hunter</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Search a username across 14 public platforms.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
        <a href="{{ route('phone.index') }}" class="group border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[PI]</span><p class="mt-8 font-display text-lg font-bold">Phone Intelligence</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Discover publicly published business contact numbers.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
        <a href="{{ route('reverse-phone.index') }}" class="group border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[RP]</span><p class="mt-8 font-display text-lg font-bold">Reverse Phone OSINT</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Find public indexed sources associated with a phone number.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
        <a href="{{ route('social-correlation.index') }}" class="group border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[SC]</span><p class="mt-8 font-display text-lg font-bold">Social Correlation</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Map public social profiles through observable evidence.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
    </div>
</section>
<section class="border-y border-ink/10 dark:border-[#b8ffcf]/10"><div class="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div class="mb-3 flex items-end justify-between gap-4"><div><p class="font-display text-xs uppercase tracking-[.2em] text-coral">[ digital / infrastructure ]</p></div></div></div></section>
<section class="mx-auto max-w-7xl px-5 py-12 lg:px-8">
    <div class="grid sm:grid-cols-2 lg:grid-cols-4">
        <a href="{{ route('exif.index') }}" class="group relative border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[II]</span><p class="mt-8 font-display text-lg font-bold">Image Intelligence</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">View photo locations by extracting embedded metadata.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
        <a href="{{ route('domain-intelligence.index') }}" class="group border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[DI]</span><p class="mt-8 font-display text-lg font-bold">Domain Intelligence</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Map DNS, subdomains, certificates, and infrastructure.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
        <a href="{{ route('security.index') }}" class="group border border-coral/30 bg-paper p-6 transition hover:bg-coral hover:text-paper dark:bg-ink"><span class="font-display text-3xl text-coral group-hover:text-paper">[SI]</span><p class="mt-8 font-display text-lg font-bold">Security Inspector</p><p class="mt-2 text-sm leading-6 text-ink/60 group-hover:text-paper/75 dark:text-paper/60">Passively inspect public HTTP, TLS, DNS, and headers.</p><span class="mt-7 block font-display text-xs uppercase tracking-wider text-coral group-hover:text-paper">launch tool ?</span></a>
    </div>
</section>
@endsection


