@extends('layouts.app')
@section('content')
<section class="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div class="flex flex-wrap items-end justify-between gap-5"><div><p class="font-display text-xs uppercase tracking-[.24em] text-coral">domain intelligence :: scan result</p><h1 class="mt-3 break-all font-display text-3xl font-bold">{{ $scan->hostname }}</h1><p class="mt-2 font-display text-xs text-ink/50 dark:text-paper/50">STATUS: {{ $scan->status }} · {{ $scan->created_at?->format('Y-m-d H:i') }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('domain-intelligence.export', $scan) }}" class="action">JSON</a><a href="{{ route('domain-intelligence.index') }}" class="action">New scan</a></div></div>

@php($score = $scan->meta['score_breakdown'] ?? [])
@php($tls = $scan->meta['tls'] ?? [])
@php($http = $scan->meta['http'] ?? [])
@php($whois = $scan->meta['whois'] ?? [])

<div class="mt-10 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div class="space-y-6">
    <div class="border border-coral/60 bg-sand/30 p-7 text-center shadow-[0_0_28px_rgba(57,255,136,.08)] dark:bg-sand/20"><p class="font-display text-xs uppercase tracking-[.2em] text-coral">security posture score</p><p class="mt-4 font-display text-7xl font-bold text-coral">{{ $scan->score ?? '—' }}<span class="text-2xl text-ink/40 dark:text-paper/40"> / 100</span></p><p class="mt-2 font-display text-3xl font-bold">{{ $scan->posture ?? 'PENDING' }}</p></div>

    @if($score)
    <div class="border border-coral/30 p-5"><p class="font-display text-xs uppercase tracking-wider text-coral">system check</p><div class="mt-4 space-y-3">@foreach($score as $check)<div class="flex justify-between font-display text-sm"><span>{{ strtoupper($check['name']) }}</span><span class="{{ ($check['score'] ?? 0) === ($check['max'] ?? 0) ? 'text-coral' : 'text-yellow-400' }}">[ {{ $check['score'] }}/{{ $check['max'] }} ]</span></div>@endforeach</div></div>
    @endif

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="text-coral">REGISTRATION</p>@if(!empty($whois))<p class="mt-3">registrar: {{ $whois['registrar'] ?? 'N/A' }}</p><p class="mt-2">created: {{ isset($whois['created_date']) ? date('Y-m-d', strtotime($whois['created_date'])) : 'N/A' }}</p><p class="mt-2">expires: {{ isset($whois['expiration_date']) ? date('Y-m-d', strtotime($whois['expiration_date'])) : 'N/A' }}</p><p class="mt-2">nameservers: {{ !empty($whois['nameservers']) ? implode(', ', $whois['nameservers']) : 'N/A' }}</p><p class="mt-2">dnssec: {{ ($whois['dnssec'] ?? false) ? 'YES' : 'NO' }}</p><p class="mt-2">privacy: {{ ($whois['privacy_protected'] ?? false) ? 'PROTECTED' : 'VISIBLE' }}</p>@else<p class="mt-3 text-ink/50 dark:text-paper/50">No registration data available.</p>@endif</div>
</div>

<div class="space-y-6">
    <div class="border border-coral/30 p-5"><p class="font-display text-xs uppercase tracking-wider text-coral">findings [{{ $scan->findings->count() }}]</p>@forelse($scan->findings as $finding)<div class="mt-5 border-l-2 border-coral/60 pl-4"><p class="font-display text-xs font-bold uppercase text-yellow-400">[ {{ $finding->severity }} ] {{ $finding->title }}</p><p class="mt-2 text-sm text-ink/65 dark:text-paper/65">{{ $finding->description }}</p><p class="mt-2 font-display text-xs text-ink/50 dark:text-paper/50">evidence: {{ $finding->evidence }}</p><p class="mt-2 text-sm text-coral">fix: {{ $finding->remediation }}</p></div>@empty<p class="mt-5 text-sm text-coral">No findings returned.</p>@endforelse</div>

    <div class="grid gap-6 md:grid-cols-2"><div class="border border-coral/30 p-5"><p class="font-display text-xs uppercase text-coral">email security</p>@php($email = $scan->emailSecurity)@if($email)<div class="mt-3 space-y-2 text-xs"><div class="flex justify-between"><span>SPF</span><span class="{{ $email->spf_status === 'PASS' ? 'text-coral' : 'text-yellow-400' }}">{{ $email->spf_status }}</span></div><div class="flex justify-between"><span>DMARC</span><span class="{{ in_array($email->dmarc_status, ['REJECT', 'QUARANTINE']) ? 'text-coral' : 'text-yellow-400' }}">{{ $email->dmarc_status }}</span></div><div class="flex justify-between"><span>MX</span><span>{{ $email->mx_status }}</span></div><div class="flex justify-between"><span>DKIM</span><span>{{ $email->dkim_status }}</span></div></div>@else<p class="mt-3 text-xs text-ink/50 dark:text-paper/50">No email security data.</p>@endif</div>

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">tls / ssl</p>@if(!empty($tls))<p class="mt-4">valid: {{ ($tls['valid'] ?? false) ? 'YES' : 'NO' }}</p><p class="mt-2">issuer: {{ $tls['issuer'] ?? 'N/A' }}</p><p class="mt-2">subject: {{ $tls['subject'] ?? 'N/A' }}</p><p class="mt-2">hostname match: {{ ($tls['hostname_match'] ?? false) ? 'YES' : 'NO' }}</p><p class="mt-2">expires: {{ isset($tls['not_after']) ? date('Y-m-d', strtotime($tls['not_after'])) : 'N/A' }}</p><p class="mt-2">days remaining: {{ $tls['days_remaining'] ?? 'N/A' }}</p>@else<p class="mt-4 text-ink/50 dark:text-paper/50">No TLS data available.</p>@endif</div></div>

    <div class="grid gap-6 md:grid-cols-2"><div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">dns records</p>@forelse($scan->dnsRecords->groupBy('type') as $type => $records)<p class="mt-2 break-all"><span class="text-coral">{{ strtoupper($type) }}:</span> {{ $records->pluck('value')->implode(', ') ?: 'N/A' }}</p>@empty<p class="mt-2 text-ink/50 dark:text-paper/50">No DNS records observed.</p>@endforelse</div>

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">http</p>@if(!empty($http))<p class="mt-4">status: {{ $http['status_code'] ?? 'N/A' }}</p><p class="mt-2">final url: {{ $http['final_url'] ?? 'N/A' }}</p><p class="mt-2">response: {{ $http['response_time_ms'] ?? 'N/A' }}ms</p>@php($headers = $http['security_headers'] ?? [])<p class="mt-2">security headers: {{ collect($headers)->where('status', 'PRESENT')->count() }}/{{ count($headers) }} present</p>@else<p class="mt-4 text-ink/50 dark:text-paper/50">No HTTP data available.</p>@endif</div></div>

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">subdomains [{{ $scan->subdomains->count() }}]</p>@if($scan->subdomains->isNotEmpty())<div class="mt-3 max-h-48 space-y-1 overflow-y-auto">@foreach($scan->subdomains as $subdomain)<p class="break-all">{{ $subdomain->hostname }} @if($subdomain->ip)<span class="text-ink/40 dark:text-paper/40">→ {{ $subdomain->ip }}</span>@endif</p>@endforeach</div>@else<p class="mt-3 text-ink/50 dark:text-paper/50">No subdomains discovered.</p>@endif</div>

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">ip / asn intelligence [{{ $scan->ips->count() }}]</p>@if($scan->ips->isNotEmpty())<div class="mt-3 space-y-2">@foreach($scan->ips as $ip)<div class="border-b border-coral/10 pb-2"><p class="font-bold">{{ $ip->ip }}</p><p class="text-ink/60 dark:text-paper/60">{{ $ip->asn ? 'AS'.$ip->asn.' · ' : '' }}{{ $ip->asn_org ?? $ip->isp ?? 'Unknown org' }} @if($ip->country)· {{ $ip->country }} @endif</p>@if($ip->reverse_dns)<p class="text-ink/40 dark:text-paper/40">PTR {{ $ip->reverse_dns }}</p>@endif</div>@endforeach</div>@else<p class="mt-3 text-ink/50 dark:text-paper/50">No IP data collected.</p>@endif</div>

    <div class="border border-coral/30 p-5 font-display text-xs"><p class="uppercase text-coral">certificates [{{ $scan->certificates->count() }}]</p>@if($scan->certificates->isNotEmpty())<div class="mt-3 max-h-48 space-y-2 overflow-y-auto">@foreach($scan->certificates as $cert)<div><p class="text-ink/80 dark:text-paper/80">{{ $cert->issuer ?? 'Unknown issuer' }}</p>@if($cert->valid_until)<p class="text-ink/40 dark:text-paper/40">valid until {{ date('Y-m-d', strtotime($cert->valid_until)) }}</p>@endif</div>@endforeach</div>@else<p class="mt-3 text-ink/50 dark:text-paper/50">No CT log entries found.</p>@endif</div>
</div></div></section>
@endsection